name: Mariage FE.BOT ğŸ¤–

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸšš
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ”¨
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies By Package.json ğŸ—
        run: cd frontend && npm ci

      - name: Jest Test âœ…
        run: cd frontend && npm run test

    #   - name: Webpack Build
    #     run: cd frontend && npm run build
    #     ì›ì¸ ë¶„ì„ í›„ ìˆ˜ì •í•  ì˜ˆì •, í˜„ì¬ PNG íŒŒì¼ì„ ì²˜ë¦¬í•˜ì§€ ëª»í•¨
