name: Mariage FE.BOT ğŸ¤–

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository ğŸšš
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ”¨
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies By Package.json ğŸ—
        run: npm ci

      - name: Jest Test âœ…
        run: npm run test

      - name: Webpack Start â­
        env:
          CI: false
        run: npm run start

      - name: Webpack Build â­
        env:
          CI: false
        run: npm run Build

      - name: Get Repository URL ğŸ›’
        id: repo_info
        run: |
          repo_url=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq -r .html_url)
          echo "::set-output name=repository_url::$repo_url"

      - name: Get Commit URL ğŸ›’
        id: commit_info
        run: |
          commit_url="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          echo "::set-output name=commit_url::$commit_url"

      - name: Send Result to Discord ğŸ“©
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Mariage FE.BOT ğŸ¤–"
          message: |
            Frontend Main Branch CI í…ŒìŠ¤íŠ¸ ğŸ“œ
            CI Status      : ${{ job.status }}
            Repository URL : [URL](${{ steps.repo_info.outputs.repository_url }})
            Commit URL     : [URL](${{ steps.commit_info.outputs.commit_url }})
