name: Mariage FE.BOT ğŸ¤–

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository ğŸšš
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ”¨
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies By Package.json ğŸ—
        run: npm ci

      - name: Jest Test âœ…
        run: npm run test

      - name: Webpack Start â­
        env:
          CI: false
        run: npm run start

      - name: Get PR URL ğŸ›’
        id: pr_info
        run: |
          pr_url="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          echo "::set-output name=pr_url::$pr_url"

      - name: Get Commit URL ğŸ›’
        id: commit_info
        run: |
          commit_url="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          echo "::set-output name=commit_url::$commit_url"

      - name: Send Result to Discord ğŸ“©
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Mariage FE.BOT ğŸ¤–"
          message: |
            Frontend Pull Request[#${{ github.event.pull_request.number }}] CI Test ğŸ“œ
            Status : [**${{ job.status }}**]
            Pull Request : ${{ steps.pr_info.outputs.pr_url }}
            Commit : ${{ steps.commit_info.outputs.commit_url }}

    if: ${{ contains(github.event.pull_request.labels.*.name, 'ğŸ–¼ï¸ front-end') }}
